// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"go_test"
	"go_test/zrpc/internal/logic"
	"go_test/zrpc/internal/svc"
)

type MicrouserServer struct {
	svcCtx *svc.ServiceContext
	__microuser.UnimplementedMicrouserServer
}

func NewMicrouserServer(svcCtx *svc.ServiceContext) *MicrouserServer {
	return &MicrouserServer{
		svcCtx: svcCtx,
	}
}

func (s *MicrouserServer) GetUser(ctx context.Context, in *__microuser.Request) (*__microuser.Response, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}
